kind = "web"
previewPath = "/"
title = "Felegeneway Academy"
version = "1.0.0"
id = "artifacts/felegeneway"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24332

[services.development]
run = "pnpm --filter @workspace/felegeneway run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/felegeneway", "run", "build" ]
publicDir = "artifacts/felegeneway/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24332"
BASE_PATH = "/"
